spring.application.name=SpringWork

# WAS Port
server.port = 11000

# MongoDB Connection
spring.data.mongodb.host=43.200.5.164
spring.data.mongodb.port=27017
spring.data.mongodb.database=MyDB
spring.data.mongodb.username=myUser
Spring.data.mongodb.password=1234

# caching log
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.cache.interceptor=TRACE

